"""resume_versioning_and_labels

Revision ID: 03e0b36a2a80
Revises: 29f28f934f49
Create Date: 2026-07-12 16:51:26.604145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e0b36a2a80'
down_revision: Union[str, Sequence[str], None] = '29f28f934f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('resume_version_counter', sa.Integer(), server_default='0', nullable=False))
    op.add_column('resumes', sa.Column('label', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

    # Backfill resume_version_counter for candidate profiles based on their resumes
    op.execute("""
        UPDATE candidate_profiles
        SET resume_version_counter = (
            SELECT COALESCE(MAX(version), 0)
            FROM resumes
            WHERE resumes.candidate_id = candidate_profiles.user_id
        )
    """)

    # Backfill label column for existing resumes to 'Version {version}'
    op.execute("""
        UPDATE resumes
        SET label = 'Version ' || CAST(version AS VARCHAR)
        WHERE label IS NULL
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'label')
    op.drop_column('candidate_profiles', 'resume_version_counter')
    # ### end Alembic commands ###
