"""Remove target_domain from CandidateProfile

Revision ID: 0a92b2217e1e
Revises: 980a4bc47ed4
Create Date: 2026-07-11 22:51:31.254725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a92b2217e1e'
down_revision: Union[str, Sequence[str], None] = '980a4bc47ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'target_domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('target_domain', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
