"""add_scoring_profiles_and_jd_fields

Revision ID: 7fa1cda07226
Revises: a6a7a3bab700
Create Date: 2026-07-13 22:18:03.109064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa1cda07226'
down_revision: Union[str, Sequence[str], None] = 'a6a7a3bab700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('experience_level', sa.String(length=100), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_profiles_id'), 'scoring_profiles', ['id'], unique=False)
    op.add_column('job_descriptions', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('job_descriptions', sa.Column('optional_notes', sa.Text(), nullable=True))
    op.add_column('job_descriptions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('job_descriptions', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'is_archived')
    op.drop_column('job_descriptions', 'updated_at')
    op.drop_column('job_descriptions', 'optional_notes')
    op.drop_column('job_descriptions', 'company')
    op.drop_index(op.f('ix_scoring_profiles_id'), table_name='scoring_profiles')
    op.drop_table('scoring_profiles')
    # ### end Alembic commands ###
