"""add_label_source_and_status_to_resume

Revision ID: a6a7a3bab700
Revises: 03e0b36a2a80
Create Date: 2026-07-12 20:19:05.175829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a7a3bab700'
down_revision: Union[str, Sequence[str], None] = '03e0b36a2a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('label_source', sa.String(length=50), nullable=True))
    op.add_column('resumes', sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='resumestatus', native_enum=False), server_default='ACTIVE', nullable=False))
    # ### end Alembic commands ###

    # Backfill label_source for existing resumes
    op.execute("""
        UPDATE resumes
        SET label_source = CASE
            WHEN label IS NULL THEN 'SYSTEM'
            WHEN label LIKE 'Version %' THEN 'SYSTEM'
            ELSE 'USER'
        END
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'status')
    op.drop_column('resumes', 'label_source')
    # ### end Alembic commands ###
